# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cv.event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cv.event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63v.event.proto\x12\x16\x63om.ben.smartcv.common\"2\n\x0e\x43vAppliedEvent\x12\r\n\x05\x63v_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\"5\n\x10\x43vProcessedEvent\x12\r\n\x05\x63v_id\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t\"3\n\x0e\x43vDeletedEvent\x12\r\n\x05\x63v_id\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t\"7\n\x12\x43vFileDeletedEvent\x12\r\n\x05\x63v_id\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\tB+\n\x19\x63om.ben.smartcv.common.cvB\x0c\x43vEventProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cv.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.ben.smartcv.common.cvB\014CvEventProtoP\001'
  _globals['_CVAPPLIEDEVENT']._serialized_start=42
  _globals['_CVAPPLIEDEVENT']._serialized_end=92
  _globals['_CVPROCESSEDEVENT']._serialized_start=94
  _globals['_CVPROCESSEDEVENT']._serialized_end=147
  _globals['_CVDELETEDEVENT']._serialized_start=149
  _globals['_CVDELETEDEVENT']._serialized_end=200
  _globals['_CVFILEDELETEDEVENT']._serialized_start=202
  _globals['_CVFILEDELETEDEVENT']._serialized_end=257
# @@protoc_insertion_point(module_scope)
