# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cv.service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cv.service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.cv import event_pb2 as cv_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63v.service.proto\x12\x16\x63om.ben.smartcv.common\x1a\x0e\x63v.event.proto\"v\n\x0f\x45xtractedCvData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x12\n\neducations\x18\x04 \x03(\t\x12\x0e\n\x06skills\x18\x05 \x03(\t\x12\x13\n\x0b\x65xperiences\x18\x06 \x03(\t2q\n\x0b\x43vProcessor\x12\x62\n\x0b\x45xtractData\x12(.com.ben.smartcv.common.CvProcessedEvent\x1a\'.com.ben.smartcv.common.ExtractedCvData\"\x00\x42-\n\x19\x63om.ben.smartcv.common.cvB\x0e\x43vServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cv.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.ben.smartcv.common.cvB\016CvServiceProtoP\001'
  _globals['_EXTRACTEDCVDATA']._serialized_start=60
  _globals['_EXTRACTEDCVDATA']._serialized_end=178
  _globals['_CVPROCESSOR']._serialized_start=180
  _globals['_CVPROCESSOR']._serialized_end=293
# @@protoc_insertion_point(module_scope)
