# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job.command.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'job.command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11job.command.proto\x12\x16\x63om.ben.smartcv.common\"#\n\x11ProcessJobCommand\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"+\n\x19RollbackProcessJobCommand\x12\x0e\n\x06job_id\x18\x01 \x01(\tB/\n\x1a\x63om.ben.smartcv.common.jobB\x0fJobCommandProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ben.smartcv.common.jobB\017JobCommandProtoP\001'
  _globals['_PROCESSJOBCOMMAND']._serialized_start=45
  _globals['_PROCESSJOBCOMMAND']._serialized_end=80
  _globals['_ROLLBACKPROCESSJOBCOMMAND']._serialized_start=82
  _globals['_ROLLBACKPROCESSJOBCOMMAND']._serialized_end=125
# @@protoc_insertion_point(module_scope)
