services:
  # --------- postgres ---------
  smartcv-postgres:
    image: debezium/postgres:16-alpine
    container_name: smartcv-postgres
    restart: always
    build: ../../docker/postgres
    command: postgres -c 'max_connections=500'
    ports:
      - 5432:5432
    networks:
      - smartcv-network
    volumes:
      - ../../docker/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ../../docker/postgres/postgres-init-db:/docker-entrypoint-initdb.d:ro
      - smartcv-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # --------- Mongodb ---------
  smartcv-mongodb:
    image: mongo:latest
    container_name: smartcv-mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - smartcv-network
    volumes:
      - smartcv-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  # --------- Redis ---------
  smartcv-redis:
    image: redis:latest
    container_name: smartcv-redis
    restart: always
    volumes:
      - smartcv-redis-data:/data
    ports:
      - 6379:6379
    networks:
      - smartcv-network

  # --------- Elasticsearch ---------
  smartcv-elasticsearch:
    image: elasticsearch:8.16.5
    container_name: smartcv-elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - smartcv-network
    volumes:
      - smartcv-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms4g -Xmx4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

volumes:
  smartcv-postgres-data:
  smartcv-mongodb-data:
  smartcv-redis-data:
  smartcv-elasticsearch-data:

