services:
  # --------- Minio ---------
  smartcv-minio:
    image: minio/minio:latest
    container_name: smartcv-minio
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - smartcv-network
    volumes:
      - smartcv-minio-data:/data:r
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

volumes:
  smartcv-minio-data: