services:
  # --------- Kafka UI ---------
  smartcv-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: smartcv-kafka-ui
    restart: always
    depends_on:
      - smartcv-kafka1
      - smartcv-schemaregistry
    ports:
      - "8080:8080"
    networks:
      - smartcv-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: smartcv-kafka1:19091
      KAFKA_CLUSTERS_0_METRICS_PORT: 9991
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://smartcv-schemaregistry:8085
      DYNAMIC_CONFIG_ENABLED: 'true'

  # --------- Mongo express ---------
  smartcv-express:
    image: mongo-express:latest
    container_name: smartcv-express
    restart: always
    depends_on: [ smartcv-mongodb ]
    ports:
      - "5051:8081"
    networks:
      - smartcv-network
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: smartcv
      ME_CONFIG_MONGODB_ADMINPASSWORD: SmArTcV123#
      ME_CONFIG_MONGODB_URL: mongodb://smartcv:SmArTcV123%23@smartcv-mongodb:27017/

  # --------- Kibana ---------
  smartcv-kibana:
    image: kibana:8.16.5
    container_name: smartcv-kibana
    restart: always
    depends_on:
      [ smartcv-elasticsearch ]
    ports:
      - "5601:5601"
    networks:
      - smartcv-network
    environment:
      ELASTICSEARCH_HOSTS: http://smartcv-elasticsearch:9200
      ELASTICSEARCH_USERNAME: smartcv
      ELASTICSEARCH_PASSWORD: SmArTcV123#
      xpack.security.enabled: false # Disable X-Pack security features

