services:
  # --------- Kafka UI ---------
  smartcv-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: smartcv-kafka-ui
    restart: always
    depends_on:
      - smartcv-kafka1
      - smartcv-schemaregistry
    ports:
      - 8080:8080
    networks:
      - smartcv-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: smartcv-kafka1:19091
      KAFKA_CLUSTERS_0_METRICS_PORT: 9991
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://smartcv-schemaregistry:8085
      DYNAMIC_CONFIG_ENABLED: true

  # --------- Pgadmin ---------
  smartcv-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartcv-pgadmin
    restart: always
    depends_on: [ smartcv-postgres ]
    ports:
      - 5050:80
    networks:
      - smartcv-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

  # --------- Mongo express ---------
  smartcv-express:
    image: mongo-express:latest
    container_name: smartcv-express
    restart: always
    depends_on: [ smartcv-mongodb ]
    ports:
      - 5051:8081
    networks:
      - smartcv-network
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD_ENCODED}@smartcv-mongodb:27017/

  # --------- Redis Insight ---------
  smartcv-redis-insight:
    image: redis/redisinsight:latest
    container_name: smartcv-redis-insight
    restart: always
    depends_on: [ smartcv-redis ]
    ports:
      - 5540:5540
    networks:
      - smartcv-network

  # --------- Kibana ---------
  smartcv-kibana:
    image: kibana:8.16.5
    container_name: smartcv-kibana
    restart: always
    depends_on:
      [ smartcv-elasticsearch ]
    ports:
      - 5601:5601
    networks:
      - smartcv-network
    environment:
      ELASTICSEARCH_HOSTS: http://smartcv-elasticsearch:9200
      xpack.security.enabled: false
      xpack.reporting.roles.enabled: false

