# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job.processor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'job.processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.job import event_pb2 as job_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13job.processor.proto\x12\x16\x63om.ben.smartcv.common\x1a\x0fjob.event.proto\"i\n\x10\x45xtractedJobData\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x12\n\neducations\x18\x03 \x03(\t\x12\x0e\n\x06skills\x18\x04 \x03(\t\x12\x13\n\x0b\x65xperiences\x18\x05 \x03(\t2r\n\x0cJobProcessor\x12\x62\n\x0b\x65xtractData\x12\'.com.ben.smartcv.common.JobCreatedEvent\x1a(.com.ben.smartcv.common.ExtractedJobData\"\x00\x42\x31\n\x1a\x63om.ben.smartcv.common.jobB\x11JobProcessorProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job.processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ben.smartcv.common.jobB\021JobProcessorProtoP\001'
  _globals['_EXTRACTEDJOBDATA']._serialized_start=64
  _globals['_EXTRACTEDJOBDATA']._serialized_end=169
  _globals['_JOBPROCESSOR']._serialized_start=171
  _globals['_JOBPROCESSOR']._serialized_end=285
# @@protoc_insertion_point(module_scope)
