# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job.service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'job.service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11job.service.proto\x12\x16\x63om.ben.smartcv.common\"P\n\x15PreviewJobDescription\x12\x12\n\neducations\x18\x01 \x03(\t\x12\x0e\n\x06skills\x18\x02 \x03(\t\x12\x13\n\x0b\x65xperiences\x18\x03 \x03(\t\"\x13\n\x05JobId\x12\n\n\x02id\x18\x01 \x01(\t2g\n\nJobService\x12Y\n\x07getById\x12\x1d.com.ben.smartcv.common.JobId\x1a-.com.ben.smartcv.common.PreviewJobDescription\"\x00\x42/\n\x1a\x63om.ben.smartcv.common.jobB\x0fJobServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.ben.smartcv.common.jobB\017JobServiceProtoP\001'
  _globals['_PREVIEWJOBDESCRIPTION']._serialized_start=45
  _globals['_PREVIEWJOBDESCRIPTION']._serialized_end=125
  _globals['_JOBID']._serialized_start=127
  _globals['_JOBID']._serialized_end=146
  _globals['_JOBSERVICE']._serialized_start=148
  _globals['_JOBSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
