server:
  port: 30003
  servlet:
    context-path: /job
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

cors:
  allowed-origins: "*"

# --------- Gateway ---------
gateway:
  domain: localhost
  port: 30000

# --------- Axon ---------
axon:
  metrics:
    auto-configuration:
      enabled: true
    micrometer:
      dimensional: true

# --------- API document ---------
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: true

openapi:
  service:
    name: job
    api-docs: job-service-rest-api
    title: Job Service REST API
    description: This is the APIs documentation for Job Service.
    version: 1.0.0
    server-url: http://localhost:${server.port}${server.servlet.context-path}
    server-description: Smart CV Job Service APIs For Development

# --------- Logging ---------
logging:
  pattern:
    correlation: "[${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"
#  level:
#    org:
#      springframework:
#        security: DEBUG

# --------- Metrics & Monitoring ---------
management:
  info:
    git:
      enabled: true
      mode: full

  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - mappings
          - health
          - info
          - metrics
          - prometheus

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}

  observations:
    key-values:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

# --------- Spring configs ---------
spring:
  application:
    name: job

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  graphql:
    path: /graphql

    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allowed-origin-patterns: "*"
      allowed-origins: "*"

    graphiql:
      enabled: true  # Bật GraphiQL UI để test API GraphQL
      path: /graphiql

    playground:
      enabled: true
      endpoint: /graphql
      subscriptions:
        endpoint: /subscriptions

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
    cache-duration: 3600

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    username: smartcv
    password: SmArTcV123#

  data:
    mongodb:
      uri: mongodb://smartcv:SmArTcV123%23@localhost:27017/axon-framework?authSource=admin

    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9091
    properties:
      schema.registry.url: http://localhost:8085
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false