server:
  port: 30004
  servlet:
    context-path: /notification
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

# --------- Eureka ---------
eureka:
  instance:
    hostname: ${DISCOVERY_DOMAIN:localhost}

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${DISCOVERY_PORT:31000}/eureka/

# --------- Gateway ---------
gateway:
  domain: ${GATEWAY_DOMAIN:localhost}
  port: ${GATEWAY_PORT:30000}

# --------- Security ---------
security:
  jwt:
    access-signer-key: ${ACCESS_SIGNER_KEY}

  public-endpoints:
    - /example

  grpc:
    public-methods:
      - FileService/getDownloadUrl

# --------- Axon ---------
axon:
  event-bus-name: smartcv-event-bus
  metrics:
    auto-configuration:
      enabled: true
    micrometer:
      dimensional: true

# --------- Logging ---------
logging:
  pattern:
    correlation: "[${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"

  level:
    org:
      springframework:
        security: DEBUG

# -------- Resilience4j ---------
resilience4j:
  circuitbreaker:
    configs:
      grpcGroup:
        registerHealthIndicator: true
        slidingWindowSize: 50
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

    instances:
      authService:
        baseConfig: grpcGroup

  timelimiter:
    configs:
      grpcGroup:
        timeoutDuration: 10s
        cancelRunningFuture: true

    instances:
      authService:
        baseConfig: grpcGroup

# --------- Metrics & Monitoring ---------
management:
  info:
    git:
      enabled: true
      mode: full

  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}

  observations:
    key-values:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

# --------- Spring configs ---------
spring:
  config:
    import: file:env.properties

  application:
    name: notification

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
    cache-duration: 3600

  grpc:
    client:
      enabled: true
      observations:
        enabled: true
      channels:
        auth-service:
          address: static://${AUTH_SERVICE_ADDRESS:localhost:31006}
          negotiation-type: plaintext
          health:
            enabled: true
            service-name: auth-service

  data:
    mongodb:
      axon:
        uri: ${MONGODB_URI}

    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      database: 0

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false