import os

from dotenv import load_dotenv

load_dotenv()
KAFKA_TOPIC_CV_COMMAND = os.getenv("KAFKA_TOPIC_CV_COMMAND")
KAFKA_TOPIC_JOB_COMMAND = os.getenv("KAFKA_TOPIC_JOB_COMMAND")
KAFKA_TOPIC_NOTIFICATION_COMMAND = os.getenv("KAFKA_TOPIC_NOTIFICATION_COMMAND")
bootstrap_servers = os.getenv("BOOTSTRAP_SERVERS")
KAFKA_GROUP_CV_PROCESSOR = os.getenv("KAFKA_GROUP_CV_PROCESSOR")
KAFKA_GROUP_JOB_PROCESSOR = os.getenv("KAFKA_GROUP_JOB_PROCESSOR")