server:
  http_listen_port: 3200
  log_level: info

stream_over_http_enabled: true

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "smartcv-tempo:4317"
        http:
          endpoint: "smartcv-tempo:4318"

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 720h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://smartcv-prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both
