services:
  # Kafka brokers:
  novax-kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: novax-kafka1
    restart: always
    ports:
      - "9091:9091"
      - "9991:9991"
    networks:
      - novax-network
    environment:
      # Kraft
      CLUSTER_ID: 'cLs1'
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@novax-kafka1:29091,2@novax-kafka2:29092,3@novax-kafka3:29093'

      # Listeners
      KAFKA_LISTENERS: 'LOCAL://:9091,PLAINTEXT://novax-kafka1:19091,CONTROLLER://novax-kafka1:29091,BROKER://novax-kafka1:39091'
      KAFKA_ADVERTISED_LISTENERS: 'LOCAL://localhost:9091,PLAINTEXT://novax-kafka1:19091,BROKER://novax-kafka1:39091'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT,BROKER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'

#      # SSL/TLS
#      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
#      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds
#      KAFKA_SSL_KEY_CREDENTIALS: creds
#      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
#      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds
#      KAFKA_SSL_CLIENT_AUTH: 'none'
#      #KAFKA_SSL_CLIENT_AUTH: 'requested'
#      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
#
#      # SASL
#      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
#      KAFKA_SASL_MECHANISMS_CONTROLLER_PROTOCOL: PLAIN
#      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
#      KAFKA_SUPER_USERS: 'User:admin,User:ben'
#      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
#      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server.conf"

      # Others
      KAFKA_JMX_PORT: 9991
      KAFKA_JMX_HOSTNAME: novax-kafka1

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3

  novax-kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: novax-kafka2
    restart: always
    ports:
      - "9092:9092"
      - "9992:9992"
    networks:
      - novax-network
    environment:
      # Kraft
      CLUSTER_ID: 'cLs1'
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: "r2"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@novax-kafka1:29091,2@novax-kafka2:29092,3@novax-kafka3:29093'

      # Listeners
      KAFKA_LISTENERS: 'LOCAL://:9092,PLAINTEXT://novax-kafka2:19092,CONTROLLER://novax-kafka2:29092,BROKER://novax-kafka2:39092'
      KAFKA_ADVERTISED_LISTENERS: 'LOCAL://localhost:9092,PLAINTEXT://novax-kafka2:19092,BROKER://novax-kafka2:39092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT,BROKER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'

      # Others
      KAFKA_JMX_PORT: 9992
      KAFKA_JMX_HOSTNAME: novax-kafka2

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3

  novax-kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: novax-kafka3
    restart: always
    ports:
      - "9093:9093"
      - "9993:9993"
    networks:
      - novax-network
    environment:
      # Kraft
      CLUSTER_ID: 'cLs1'
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: "r3"
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@novax-kafka1:29091,2@novax-kafka2:29092,3@novax-kafka3:29093'

      # Listeners
      KAFKA_LISTENERS: 'LOCAL://:9093,PLAINTEXT://novax-kafka3:19093,CONTROLLER://novax-kafka3:29093,BROKER://novax-kafka3:39093'
      KAFKA_ADVERTISED_LISTENERS: 'LOCAL://localhost:9093,PLAINTEXT://novax-kafka3:19093,BROKER://novax-kafka3:39093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT,BROKER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'

      # Others
      KAFKA_JMX_PORT: 9993
      KAFKA_JMX_HOSTNAME: novax-kafka3

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3

  # Schema registry
  novax-schemaregistry:
    image: confluentinc/cp-schema-registry:latest
    container_name: novax-schemaregistry
    restart: always
    depends_on:
      - novax-kafka1
      - novax-kafka2
      - novax-kafka3
    ports:
      - "8085:8085"
    networks:
      - novax-network
    environment:
      SCHEMA_REGISTRY_HOST_NAME: novax-schemaregistry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: novax-kafka1:19091,novax-kafka2:19092,novax-kafka3:19093
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_LISTENERS: http://novax-schemaregistry:8085,http://localhost:8085

      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 2
      SCHEMA_REGISTRY_DEBUG: 'true'

  # Axon Server
  novax-axonserver:
    image: 'axoniq/axonserver:latest'
    container_name: novax-axonserver
    restart: always
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      AXONIQ_AXONSERVER_STANDALONE: TRUE

  # Kafka UI
  novax-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: novax-kafka-ui
    restart: always
    depends_on:
      - novax-kafka1
      - novax-kafka2
      - novax-kafka3
      - novax-schemaregistry
    ports:
      - "8080:8080"
    networks:
      - novax-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: novax-kafka1:19091
      KAFKA_CLUSTERS_0_METRICS_PORT: 9991
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://novax-schemaregistry:8085
      DYNAMIC_CONFIG_ENABLED: 'true'


