apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://smartcv-prometheus:9090
    editable: false
    jsonData:
      httpMethod: GET
    version: 1

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://smartcv-tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
      serviceMap:
        datasourceUid: 'prometheus'

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://smartcv-loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: traceid":"([a-f0-9\-]+)
          name: TraceID
          url: $${__value.raw}
